name: Build and deploy .NET Core application to Function App azure-function-alexasmarthomeskill-homeassistant
on:
  push:
    branches:
    - main
env:
  AZURE_FUNCTIONAPP_NAME: azure-function-alexasmarthomeskill-homeassistant
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: src
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.azure_function_alexasmarthomeskill_homeassistant_D6E6 }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
